### ISSUE TITLE
feel大神，从高清范辛苦找到您，请加个QQ防止失联，我一个群都在用您插件。

### ISSUE THREAD

**Issue by zxy0145** [feelfar/115-for-kodi#1]
从高清范辛苦找到您，请加个QQ防止失联，我一个群都在用您插件。 我QQ 690897422

**Comment by feelfar** [comment]
我hdpfans无法正常使用，通知不到大家，如果你能正常使用hdpfans就帮忙通知下。今后我就在Github上维护了，不用担心失联
