### ISSUE TITLE
關於115附加元件打開失敗

### ISSUE THREAD

**Issue by ileolee** [feelfar/115-for-kodi#10]
Feelfar大神你好,我是在hdpfans已經跟隨了多年的小粉絲,最近換了新平板samsung Tab S7+,不知道什麼原因使用KODI 19一進去就會黑屏,最後只好使用KODI 18版本,但是當我安裝了115proxy-for-kodi插件後,每次點擊115附加元件右下角也會彈出[不能打開,請查看錯日誌],簡單來說就是無法打開插件,另外原碼插件也安裝失敗, 我是使用"kodi skin confluence",這幾年我一直使用舊平板 KODI 17 + 115proxy-for-kodi V2.5.7三年前的版本,後來我試過在新平板安裝"115proxy-for-kodi V2.5.7舊版",能成功進入,但奇怪是當我掃描QR CODE時,每次都提示"登錄失敗",可是我115帳號裡有看到是成功增加了新置備"網頁版", 買新平板就是為了大神的插件115+KODI實現源碼播放...現在很苦腦..大神能出手幫忙嗎?看看為何最新插件"115proxy-for-kodi 3.0"為什麼在kodi 18無法打開? 萬分感謝!!!!!

**Comment by feelfar** [comment]
是我疏忽了，最近更新没在kodi18下测试，现已修复，请重新下载安装。

**Comment by 815169876** [comment]
> 是我疏忽了，最近更新没在kodi18下测试，现已修复，请重新下载安装。

刚更新的   云下载文件夹同样打不开

**Comment by feelfar** [comment]
> 
> 刚更新的 云下载文件夹同样打不开
请另开个issue，并贴下log文件

**Comment by 815169876** [comment]
> > 刚更新的 云下载文件夹同样打不开
> 
> 请另开个issue，并贴下log文件

请问log文件位置是哪里。。

**Comment by ileolee** [comment]
謝謝大神馬上搶修，今晚回去測試一下，另外我想問，記得你以前一直推薦使用「kodi skin confluence」，是為了縮圖有更好的選片效果這點我明白，請問現在有新的skin推薦嗎
