### ISSUE TITLE
feelfar 大神 请教利用EditThisCookie 登录115浏览器 导出josn文件 后 重新打开115浏览器 导入josn 后登录不了

### ISSUE THREAD

**Issue by zxy0145** [feelfar/115-for-kodi#12]
feelfar 大神 请教利用EditThisCookie 登录115浏览器 
按照以前的方法导出josn文件 后 重新打开115浏览器 导入josn 后登录不了。
kodi 那个文件cookie dat 文件 可以导入导出登录，就是115浏览器不能利用EditThisCookie 登录了。
能否联系我 教我新的方法 我邮箱 690897422@qq.com。 非常感谢！

**Comment by feelfar** [comment]
编辑下json文件 ：
1、保留 UID CID  SEID 三个块，其它删掉
2、将domain值改为115.com(删掉开头的点)
再重新导入试试
![IMG_20210328_095120](https://user-images.githubusercontent.com/6426022/112739951-4e411600-8fab-11eb-8c45-47338c34ec1a.jpg)

**Comment by 815169876** [comment]
> 编辑下json文件 ：
> 1、保留 UID CID SEID 三个块，其它删掉
> 2、将domain值改为115.com(删掉开头的点)
> 再重新导入试试
> ![IMG_20210328_095120](https://user-images.githubusercontent.com/6426022/112739951-4e411600-8fab-11eb-8c45-47338c34ec1a.jpg)
请教
cookie.dat应该怎么写？

**Comment by feelfar** [comment]
> 请教
> cookie.dat应该怎么写？
有个更简便的方法，可以访问 http://127.0.0.1:6227/cookie 进行cookie的导入导出，支持editthiscookie使用的json格式。

**Comment by 815169876** [comment]
> > 请教
> > cookie.dat应该怎么写？
> 
> 有个更简便的方法，可以访问 http://127.0.0.1:6227/cookie 进行cookie的导入导出，支持editthiscookie使用的json格式。

谢谢大佬提供这个方法，但是我http://127.0.0.1:6227这个端口打开没有任何内容显示  不知道怎样可以解决
