### ISSUE TITLE
KODI19安装proxy插件报错

### ISSUE THREAD

**Issue by tonnygjs** [feelfar/115-for-kodi#13]
你好大神，在全新的19版本KODI上安装115的proxy插件时候报错，无法安装，好像是报啥PYthon 依赖错误，这个需要安装啥模块？在18.9的KODI上面正常的，谢谢！！！

**Comment by feelfar** [comment]
依赖项是pycryptodome，按讲kodi18 19都自带，我win64 和 arm64安卓 测试正常。请说明下操作系统和kodi具体版本

**Comment by tonnygjs** [comment]
谢谢大佬解答，问题已经解决！

**Comment by feelfar** [comment]
好的

**Comment by johnny46** [comment]
> 谢谢大佬解答，问题已经解决！
我也遇到同样问题 请问您是如何解决的

**Comment by johnny46** [comment]
> 谢谢大佬解答，问题已经解决！

我也遇到同样问题  请问您是如何解决的

**Comment by johnny46** [comment]
@tonnygjs  我也遇到同样问题 请问您是如何解决的
