### ISSUE TITLE
请求支持外挂本地字幕或115网盘同路径下字幕

### ISSUE THREAD

**Issue by emvia** [feelfar/115-for-kodi#2]
目前第三方字幕插件无法用于读取115网盘路径或本地存储路径下的外挂字幕文件，请求大佬指教或支持，感谢

**Comment by feelfar** [comment]
支持同目录下同名字幕文件（字幕文件名包含视频文件名），会下载到插件目录下的subtitles文件夹。使用kodi自带播放器会自动加载

**Comment by feelfar** [comment]
最近还加入了 idx+sub 图形字幕文件支持

**Comment by feelfar** [comment]
方法就是到subhd、opensubtitle等字幕网站下载字幕文件，解压上传到115，移动到视频所在文件夹，改名，让字幕文件与视频文件同名（如有多个版本字幕文件名可加.chn等后缀）。插件打开视频目录时会先缓存字幕文件名，打开同名视频文件时就会加载。

**Comment by emvia** [comment]
> 方法就是到subhd、opensubtitle等字幕网站下载字幕文件，解压上传到115，移动到视频所在文件夹，改名，让字幕文件与视频文件同名（如有多个版本字幕文件名可加.chn等后缀）。插件打开视频目录时会先缓存字幕文件名，打开同名视频文件时就会加载。

收到，感谢大佬细心讲解！
感觉可以在Readme 或者Wiki里面增加一点类似这种比较隐藏的功能使用帮助或要点说明，方便大家研究和使用！
再次感谢！
