### ISSUE TITLE
KODI 19.2版無法支援

### ISSUE THREAD

**Issue by HuiLungChen** [feelfar/115-for-kodi#22]
大神求救啊..
不知是否有什麼辦法可以讓這個插件可以正常運行在19.2版？

**Comment by feelfar** [comment]
刚升级了19.3，初步测试还正常

**Comment by HuiLungChen** [comment]
看到大神說測試正常，
所以我再仔細檢查、並重新下載，
我目前使用KODI 19.3，
先安裝 115proxy-for-kodi
https://github.com/feelfar/115proxy-for-kodi/archive/master.zip
再安裝115-for-kodi
https://github.com/feelfar/115-for-kodi/archive/master.zip

最後發現原來之前安裝的是yxblog, 2020-12 modify by feelfar - 0.2.6.0 是舊版，
從上面連結安裝的版本是yxblog, 2020-12 modify by feelfar - 0.3.0.0，
這樣就可以連結網盤並順利播放了，
感謝大神的回覆！
