### ISSUE TITLE
插件无法安装

### ISSUE THREAD

**Issue by yizhidouzai** [feelfar/115-for-kodi#23]
我用了18.9和19.4两个版本都提示无法安装115forkodi这个插件，但是能安装那个115proxyforkodi那个插件，请问是什么原因呢？如图所示
![Screenshot_2022-04-09-15-10-32-244_org xbmc kodi](https://user-images.githubusercontent.com/14296749/162600980-74984f3a-e48b-405c-90a4-e523e90eb2a4.jpg)

**Comment by sjsj5** [comment]
我今天也出现和你一样的情况 请问你解决了吗？

**Comment by feelfar** [comment]
请查看另一同情况议题
