### ISSUE TITLE
播放列表图标

### ISSUE THREAD

**Issue by roung000** [feelfar/115-for-kodi#26]
**大神能否将列表文件大小显示出来，列表图标的三种状态显示出来（能够记住上次的播放位置），再次感谢大神！！！**

![2](https://user-images.githubusercontent.com/45146286/194034177-9bb1eca5-36db-459e-b306-3d10bca14973.jpg)

![3](https://user-images.githubusercontent.com/45146286/194036407-2a194fc8-4a20-41bf-a052-e17782ccf676.jpg)

**Comment by sjsj5** [comment]
原来的播放状态标记非常好用 恳请大佬恢复该功能 谢谢

**Comment by roung000** [comment]
希望大神有空完善此功能，谢谢

**Comment by feelfar** [comment]
> 希望大神有空完善此功能，谢谢

这个问题说实话不关插件的事。
只要改回旧版的confluence皮肤，文件大小和播放状态就看得到了。
![Screenshot_2022-10-07-10-01-03-238_org.xbmc.kodi.jpg](https://user-images.githubusercontent.com/6426022/194559937-1f50e429-873e-45d2-98ec-5a8f891b709a.jpg)

大家权衡一下吧，查了两天，现有皮肤Estuary下确实没找到比较简单的办法。

提醒一下，更换皮肤前先将语言设为英文，以免出现乱码。

**Comment by roung000** [comment]
首先感谢大神的解决方案！刚使用老皮肤，操作有些不太习惯。之前使用您的2.6.0版本，一直使用正常，播放状态也都能显示，直到前几天不能原版播放。请教大神，可否在此版本基础上，修改源码播放代码，谢谢
![1](https://user-images.githubusercontent.com/45146286/194689739-4322e420-20dc-4c2b-8b79-06041b295cb3.jpg)
![2](https://user-images.githubusercontent.com/45146286/194689742-f9eccee5-09fa-46e9-90b2-ed22631c24d5.jpg)

![3](https://user-images.githubusercontent.com/45146286/194689744-77563ca8-494f-48c1-973d-e5694b260518.jpg)

**Comment by feelfar** [comment]
> 首先感谢大神的解决方案！刚使用老皮肤，操作有些不太习惯。之前使用您的2.6.0版本，一直使用正常，播放状态也都能显示，直到前几天不能原版播放。请教大神，可否在此版本基础上，修改源码播放代码，谢谢
> ![1](https://user-images.githubusercontent.com/45146286/194689739-4322e420-20dc-4c2b-8b79-06041b295cb3.jpg)
> ![2](https://user-images.githubusercontent.com/45146286/194689742-f9eccee5-09fa-46e9-90b2-ed22631c24d5.jpg)
> 
> ![3](https://user-images.githubusercontent.com/45146286/194689744-77563ca8-494f-48c1-973d-e5694b260518.jpg)
> 

还真没注意到旧版曾正常显示，0322版本修复本问题，同时还有字幕要二次打开才正常加载问题。

**Comment by roung000** [comment]
非常感谢大神及时的回复并修复解决问题，再次感谢！
