### ISSUE TITLE
紧急求助

### ISSUE THREAD

**Issue by sjsj5** [feelfar/115-for-kodi#28]
大佬 今天想更新最新插件 结果出现问题 然后我试了kodi18 19  多个版本 还有以前的插件 都报错 内心很崩溃 求大佬指点！
![51F2A514-A823-4828-9789-3CA751D97805](https://user-images.githubusercontent.com/114943209/194797504-35efbaf2-dd9b-4b02-9234-2009c6c6fd9c.jpeg)
![B34A6455-5B55-4132-A627-0B94BB6E64E6](https://user-images.githubusercontent.com/114943209/194797523-00f5742b-0f96-430a-a62f-52faead513dc.jpeg)
![A984BB2F-1298-4647-B70B-81A416AD77C8](https://user-images.githubusercontent.com/114943209/194797527-881bc370-13a3-4f89-a98f-61fd98959228.jpeg)
![8B4C5D70-8846-41C9-BAD4-5B6C4AC6461E](https://user-images.githubusercontent.com/114943209/194797529-6b874e09-4eca-421d-9d64-9e1e62130fd4.jpeg)

**Comment by sjsj5** [comment]
现在的情况是连过去正常使用的18.3版本 然后安装老的插件板本 都报错  请大佬帮忙看一看 不胜感激！

**Comment by sjsj5** [comment]
下面发了视频 这是缺了什么吗 请问

Uploading IMG_5790.MOV…

有什么解决办法吗

**Comment by sjsj5** [comment]
https://user-images.githubusercontent.com/114943209/194800162-0b0bd81c-5771-4ff8-8016-dd4ef6118a2d.MOV

**Comment by feelfar** [comment]
> 下面发了视频 这是缺了什么吗 请问
> 
> Uploading IMG_5790.MOV…
> 
> 有什么解决办法吗 

应该是墙挡了，先下载xbmcswift2安装
https://github.com/XBMC-Addons/script.module.xbmcswift2/releases/download/19.0.7/script.module.xbmcswift2-19.0.7.zip

**Comment by sjsj5** [comment]
> > 下面发了视频 这是缺了什么吗 请问
> > Uploading IMG_5790.MOV…
> > 有什么解决办法吗
> 
> 应该是墙挡了，先下载xbmcswift2安装 https://github.com/XBMC-Addons/script.module.xbmcswift2/releases/download/19.0.7/script.module.xbmcswift2-19.0.7.zip

谢谢大佬 解决了 一身冷汗啊 多谢多谢！！ 另外有个小问题 我装的19.0版kodi 为啥语言只有英语一个选项？其他版本都有好多语种可选

**Comment by sjsj5** [comment]
大佬 方便加个微信吗 多次麻烦您  想给您个红包略表心意😊

**Comment by feelfar** [comment]
> 大佬 方便加个微信吗 多次麻烦您  想给您个红包略表心意😊

谢谢，不用客气
