### ISSUE TITLE
第三方播放器无法记录上次播放位置

### ISSUE THREAD

**Issue by roung000** [feelfar/115-for-kodi#29]
使用第三方播放器无法记录上次播放位置，每次播放都是从头开始。更换mxplayer ，potplayer，都是一样，猜测可能是代理播放源码每次被删除所致， 望大神解决，谢谢。

![2](https://user-images.githubusercontent.com/45146286/195817204-480f2a60-f258-468c-8418-2568bafadda1.png)

**Comment by feelfar** [comment]
播放进度状态是kodi内置功能，只有kodi内置播放器才能反馈播放进度状态给kodi界面。

**Comment by feelfar** [comment]
插件不管这事😂， 插件所做只是告诉kodi这个列表项就像一个视频文件，是可以播放的。

**Comment by roung000** [comment]
感谢大神解惑，谢谢！
之所以反馈是因为之前的版本，使用第三方播放器能够从上一次关闭位置继续播放，不用每次从头播放。
