### ISSUE TITLE
源码播放一段时间就会跳帧，望大神解决。

### ISSUE THREAD

**Issue by roung000** [feelfar/115-for-kodi#3]
源码播放一段时间就会暂停，跳到20秒以后，望大神解决。

**Comment by feelfar** [comment]
这段时间在进行kodi19适配，你的问题过后再测试，也希望问题再具体点，是所有文件都有问题还是某些文件有问题，还有文件扩展名，运行环境等

**Comment by roung000** [comment]
感谢大神回复，运行win10,安卓，具体的视频文件：
帧数fps60以上的会自动暂停后跳帧，与文件大小无关。还有ts格式比较卡，wmv格式有声音无图像。大神有空能否做一个16.1版本的适配，这个版本本地播放速度很快，资源消耗也小，再次感谢！
