### ISSUE TITLE
网页播放失效

### ISSUE THREAD

**Issue by gelifeisia** [feelfar/115-for-kodi#4]
网页播放失效，能进入6227的页面，但是点进网盘文件夹的时候没内容，请问如何修复，谢谢

**Comment by feelfar** [comment]
谢谢反馈，最近在做kodi19兼容，bug会较多，请先下载旧版包安装
主插件：
https://github.com/feelfar/115-for-kodi/archive/61e675a7b6ebc603d3b2e506bee3dd98f2e4c2e5.zip
原码代理：
https://github.com/feelfar/115proxy-for-kodi/archive/d35ee00d3d32a8b105fa11de939b988052c32a24.zip

**Comment by gelifeisia** [comment]
感谢大神，辛苦了
