### ISSUE TITLE
请教pickcode问题

### ISSUE THREAD

**Issue by jowu598** [feelfar/115-for-kodi#40]
参考getdownloadurl方法，获取文件下载地址时遇到问题，发现和右侧正确的地址（acgotaku/115 - GitHub](https://github.com/acgotaku/115/releases)）

只有几个字符的差异，请问是为啥？

![diff-hash](https://user-images.githubusercontent.com/5086619/227211012-7a72e0a7-e11c-4c30-ac94-92d8d0a6b578.png)

备注，
左侧：115-for-kodi ， url 无效
右侧： acgotaku/115，  url 有效

**Comment by feelfar** [comment]
由于115有下载超流量限速问题（不知现在是否还存在此问题），所以有对pickcode解析出的downloadurl做了缓存处理（通过测试，保留6个小时），你可在115客户端的”备忘“内看到。所以你看到的差异是因为115kodi取得的是之前缓存的地址。
这两天出现downloadurl失效问题，测试后发现同时缓存downloadurl+cookie可正常播放，v3.2.4版已修正此问题。

**Comment by jowu598** [comment]
> 由于115有下载超流量限速问题（不知现在是否还存在此问题），所以有对pickcode解析出的downloadurl做了缓存处理（通过测试，保留6个小时），你可在115客户端的”备忘“内看到。所以你看到的差异是因为115kodi取得的是之前缓存的地址。 这两天出现downloadurl失效问题，测试后发现同时缓存downloadurl+cookie可正常播放，v3.2.4版已修正此问题。

问题已经解决，抱歉问题背景我也没交代清楚，我借鉴了你这个版本的downloadurl解码能力，没有使用kodi相关的api。
遇到的问题是因为给的url header里user agent不是本机（linux）导致的。

谢谢楼主，很棒的项目！
