### ISSUE TITLE
希望列表排序能恢复到以前的规则

### ISSUE THREAD

**Issue by slade06** [feelfar/115-for-kodi#44]
老大，新版本默认按照时间排序，目录内的片子如果看过了，就会排到最上面，这样有点不方便。
之前好像是按照修改时间排序的，如果这个目录有过删除等操作，才会修改这个目录的时间，只是观看的话不会有变化，这样比较符合操作逻辑，115官方也是这样，有创建时间，和修改时间两种排序方法，同样观看的话不会触发修改文件修改时间。

**Comment by roung000** [comment]
对的，希望大佬恢复到官方的时间排序，或增加一项排序，感谢。

**Comment by slade06** [comment]
已经解决，貌似是官方的问题
