### ISSUE TITLE
今天无法原码播放了

### ISSUE THREAD

**Issue by tommytianhm** [feelfar/115-for-kodi#5]
环境：VIP用户，Kodi18.9
原码播放无响应，望大神抽时间处理一下，谢谢。
顺祝，春节愉快！

**Comment by feelfar** [comment]
readme 有旧版链接，经测试没问题

**Comment by tommytianhm** [comment]
很奇怪，现在常用的电脑前天原码播放都没问题的，昨天就不行了。试了重装kodi，重启，都不行。选择其它播放形式-720p，1080p，原画都可以播放。换了一台电脑或盒子原码播放都没问题。
不知何解？

**Comment by tommytianhm** [comment]
我发现从昨天开始115开始限速了，单文件下载（115浏览器下载默认2线程）速度最高3.1M/s。那么问题来了，原码播放最多也就3M/s了，高码率视频基本没法看了，卡得要命，如果这样的话，在线原码播放算是废了。不知其他VIP会员是否也被限速。

**Comment by feelfar** [comment]
经测试，115按下载量阶梯限速，从12M、6M、3M最后会限到500KB,而且下载量计算是按文件大小统计，比方说有个文件大小40G,你只下了1KB就取消了，还是算40G。一般第二天早上会恢复到12M。
原码播放就相当于下载，代理插件已经尽力优化了，但无法彻底解决，建议：不要把原码播放当抖音那样刷 (>﹏<)。

**Comment by tommytianhm** [comment]
谢谢你的测试，辛苦了。另外发现我这边（深圳中国电信）现在的最大下载速度也就13+M/s - 115浏览器2线程下载，单线程6.5M/s。用你的插件无法实现2线程原码播放，也就是说，最大的速度只能6.5M/s.

**Comment by feelfar** [comment]
![IMG_20210302_231052](https://user-images.githubusercontent.com/6426022/109669090-bf5bfc00-7bac-11eb-89c0-dc6a5a4f514e.jpg)

代理插件就是默认双线程读取文件的，播放器和下载工具对数据的读取还是有区别的，当音轨和字幕轨等加载完后，一般就单线程读取视频轨了。如果有实时网速查看的话，刚打开和拖动进度条时，应该会看到网速变化

**Comment by tommytianhm** [comment]
我观察到的网速正如你所说，就是感觉6M/s看4K高码率视频有点够呛。
谢谢你一直以来的解惑，学到了很多。
这个话题就是关闭吧。
谢谢

**Comment by feelfar** [comment]
好的，不客气
