### ISSUE TITLE
大佬能解决一下验证码输入的问题吗

### ISSUE THREAD

**Issue by kays0x** [feelfar/115-for-kodi#9]
目前似乎离线多次以后需要输入验证码，但是遥控器并不能按数字，方向键也没有反馈。不知道有什么方法能够解决这个问题吗？谢谢！

**Comment by feelfar** [comment]
好，我试下能否解决

**Comment by feelfar** [comment]
我试下看能否解决，你可以先使用以下2种方法通过验证：
1、接个鼠标
2、登录电脑端加离线链接输入验证码

**Comment by feelfar** [comment]
解决了，请重新下载更新。

**Comment by kays0x** [comment]
十分感谢！
